# Deploy snapshots to Sonatpe OSS repository

name: Deploy

on:
  workflow_run:
    workflows:
      - Build
    branches:
      - master
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      # Check out Git repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up environment with Java and Maven
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          cache: 'maven'

      # Build, deploy to ossrh, deploy site to Github Pages, generate and stage site
      - name: Build, verify, deploy
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: mvn -s ./.maven-settings.xml -B -U clean deploy